excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://nswainify.github.io
title: Communicate! 2.0
email: swainn@unimelb.edu.au
author: Nathaniel Swain
description: My new home for interactive and informative ideas and thoughts.
paginate: 4
google_analytics: 